# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Github/Rede_Perceptron_UART/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_0/Mem_ROM_0.xci
# IP: The module: 'Mem_ROM_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Github/Rede_Perceptron_UART/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_0/Mem_ROM_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mem_ROM_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Github/Rede_Perceptron_UART/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_0/Mem_ROM_0.xci
# IP: The module: 'Mem_ROM_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Github/Rede_Perceptron_UART/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_0/Mem_ROM_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mem_ROM_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
