# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.runs/synth_1/TOP.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.cache/wt [current_project]
set_property parent.project_path C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/Pesos/Memw4.COE
add_files C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/Pesos/Memw2.COE
add_files C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/Pesos/Memw1.COE
add_files C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/Pesos/Memw8.COE
add_files C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/Pesos/Memw9.COE
add_files C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/Pesos/Memw7.COE
add_files C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/Pesos/Memw5.COE
add_files C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/Pesos/Memw3.COE
add_files C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/Pesos/Memw6.COE
add_files c:/Users/Alain/Desktop/TFG_Proxecto/Vivado/Rede_Perceptron_UART/Rede_Perceptron_UART.srcs/sources_1/imports/Pesos/Memw0.COE
read_vhdl -library xil_defaultlib {
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/new/Biestable.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/UART_Recepcion/CONT_ASC.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/new/Compro_Display.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/UART_Recepcion/Cont_ciclos.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/UART_Recepcion/Detector_flanco.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/new/F_activacion.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/new/Multiplicador.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/new/Mux.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/new/Mux_Sumatorio.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/new/Perceptron_Ud_C.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/new/Perceptron_Ud_O.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/new/RN.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/UART_Recepcion/Reg_desplazamiento.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/UART_Recepcion/Rexisto_saida_UART.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/new/Rexistro.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/new/Suma_Final.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/UART_Recepcion/TOP_UART_Recepcion.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/UART_Recepcion/UART_recepcion_Ud_Control.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/UART_Recepcion/Ud_Control_UART_recepcion.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/BLOQUE_1_2_3/decod7seg.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/imports/BLOQUE_1_2_3/div_244Hz.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/new/sig_a_abs.vhd
  C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/new/TOP.vhd
}
read_ip -quiet C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_9/Mem_ROM_9.xci
set_property used_in_implementation false [get_files -all c:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_9/Mem_ROM_9_ooc.xdc]

read_ip -quiet C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_8/Mem_ROM_8.xci
set_property used_in_implementation false [get_files -all c:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_8/Mem_ROM_8_ooc.xdc]

read_ip -quiet C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_7/Mem_ROM_7.xci
set_property used_in_implementation false [get_files -all c:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_7/Mem_ROM_7_ooc.xdc]

read_ip -quiet C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_6/Mem_ROM_6.xci
set_property used_in_implementation false [get_files -all c:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_6/Mem_ROM_6_ooc.xdc]

read_ip -quiet C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_5/Mem_ROM_5.xci
set_property used_in_implementation false [get_files -all c:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_5/Mem_ROM_5_ooc.xdc]

read_ip -quiet C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_4/Mem_ROM_4.xci
set_property used_in_implementation false [get_files -all c:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_4/Mem_ROM_4_ooc.xdc]

read_ip -quiet C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_3/Mem_ROM_3.xci
set_property used_in_implementation false [get_files -all c:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_3/Mem_ROM_3_ooc.xdc]

read_ip -quiet C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_2/Mem_ROM_2.xci
set_property used_in_implementation false [get_files -all c:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_2/Mem_ROM_2_ooc.xdc]

read_ip -quiet C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_1/Mem_ROM_1.xci
set_property used_in_implementation false [get_files -all c:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_1/Mem_ROM_1_ooc.xdc]

read_ip -quiet C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Sumador/Sumador.xci

read_ip -quiet C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Contador_ADDR/Contador_ADDR.xci
set_property used_in_implementation false [get_files -all c:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Contador_ADDR/Contador_ADDR_ooc.xdc]

read_ip -quiet C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_0/Mem_ROM_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/sources_1/ip/Mem_ROM_0/Mem_ROM_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/constrs_1/imports/Downloads/PinoutNexys4.xdc
set_property used_in_implementation false [get_files C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/constrs_1/imports/Downloads/PinoutNexys4.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/Alain/GitHub/rede_perceptron_vhdl/Proxecto_VHDL/Rede_Perceptron_UART.srcs/utils_1/imports/synth_1/TOP.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top TOP -part xc7a100tcsg324-3
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
