# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Alain/Desktop/TFG_Proxecto/Vivado/Rede_Perceptron_UART/Rede_Perceptron_UART.srcs/sources_1/ip/Contador_ADDR/Contador_ADDR.xci
# IP: The module: 'Contador_ADDR' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alain/Desktop/TFG_Proxecto/Vivado/Rede_Perceptron_UART/Rede_Perceptron_UART.srcs/sources_1/ip/Contador_ADDR/Contador_ADDR_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Contador_ADDR'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Alain/Desktop/TFG_Proxecto/Vivado/Rede_Perceptron_UART/Rede_Perceptron_UART.srcs/sources_1/ip/Contador_ADDR/Contador_ADDR.xci
# IP: The module: 'Contador_ADDR' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alain/Desktop/TFG_Proxecto/Vivado/Rede_Perceptron_UART/Rede_Perceptron_UART.srcs/sources_1/ip/Contador_ADDR/Contador_ADDR_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Contador_ADDR'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
